version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: powermon
    binary: powermon
    main: ./cmd/powermon
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    builds:
      - powermon
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: rdegges
    name: powermon
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

homebrew_casks:
  - name: powermon
    # Binary to install
    binaries:
      - powermon
    # Tap repository configuration
    repository:
      owner: rdegges
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Casks
    homepage: https://github.com/rdegges/powermon
    description: Cross-platform power consumption monitor with interactive terminal UI
    caveats: |
      To run powermon on desktop Macs (Mac mini, iMac, Mac Studio, Mac Pro),
      use sudo for power monitoring: sudo powermon
    # Remove quarantine attribute for unsigned binary
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/powermon"]
          end
